-- Qentro Finance SaaS v0.7.0 - clean Supabase schema
-- Use this for a NEW project only. Existing project: use FINAL-SCHEMA-MIGRATION.sql.
create extension if not exists pgcrypto;

create table public.user_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  first_name text not null default '', last_name text not null default '', email text,
  created_at timestamptz not null default now(), last_active_at timestamptz
);
create table public.organizations (
  id uuid primary key default gen_random_uuid(), company_name text not null,
  country_code text not null check(country_code in('US','CA')), created_at timestamptz not null default now(), status text not null default 'active'
);
create table public.organization_members (
  organization_id uuid not null references public.organizations(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null default 'owner', created_at timestamptz not null default now(), primary key(organization_id,user_id)
);
create table public.signup_attempts(id bigint generated by default as identity primary key,identifier_hash text not null,created_at timestamptz not null default now());

create table public.categories(
 id uuid primary key default gen_random_uuid(), organization_id uuid references public.organizations(id) on delete cascade,
 name text not null, category_type text not null check(category_type in('expense','revenue')), is_system boolean not null default false,
 is_active boolean not null default true, sort_order integer not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create unique index categories_system_unique on public.categories(name,category_type) where organization_id is null;
create unique index categories_org_unique on public.categories(organization_id,name,category_type) where organization_id is not null;

create table public.accounts(
 id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id) on delete cascade,
 nickname text, account_type text not null check(account_type in('checking','savings','credit_card','debit_card','cash','payment_processor','other')),
 used_for text not null default 'business' check(used_for in('business','personal')), institution_name text,last_four text,currency text not null default 'USD',is_active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now()
);
create table public.clients(
 id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,name text not null,contact_name text,email text,phone text,billing_address text,notes text,is_active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now()
);
create table public.expenses(
 id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,account_id uuid references public.accounts(id) on delete set null,
 expense_date date not null default current_date,vendor text,description text,category_id uuid references public.categories(id) on delete set null,customer_project text,
 subtotal numeric(14,2) not null default 0,tax_amount numeric(14,2) not null default 0,tip_amount numeric(14,2) not null default 0,total_amount numeric(14,2) not null default 0,currency text not null default 'USD',source text not null default 'manual',status text not null default 'approved',receipt_path text,reconciled boolean not null default false,reconciled_at timestamptz,created_by uuid references auth.users(id) on delete set null,created_at timestamptz not null default now(),updated_at timestamptz not null default now()
);
create table public.revenue(
 id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,account_id uuid references public.accounts(id) on delete set null,revenue_date date not null default current_date,customer text,description text,category_id uuid references public.categories(id) on delete set null,revenue_amount numeric(14,2) not null default 0,tax_collected numeric(14,2) not null default 0,total_received numeric(14,2) not null default 0,currency text not null default 'USD',source text not null default 'manual',status text not null default 'approved',reconciled boolean not null default false,reconciled_at timestamptz,created_by uuid references auth.users(id) on delete set null,created_at timestamptz not null default now(),updated_at timestamptz not null default now()
);
create table public.bank_transactions(
 id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,account_id uuid references public.accounts(id) on delete set null,transaction_date date not null,posted_date date,description text,merchant text,amount numeric(14,2) not null,transaction_type text,import_source text not null default 'csv',external_transaction_id text,reconciliation_status text not null default 'unmatched',created_at timestamptz not null default now(),updated_at timestamptz not null default now()
);
create table public.reconciliations(
 id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,bank_transaction_id uuid not null references public.bank_transactions(id) on delete cascade,expense_id uuid references public.expenses(id) on delete cascade,revenue_id uuid references public.revenue(id) on delete cascade,match_confidence numeric(5,4),match_status text not null default 'ready_for_review',approved_by uuid references auth.users(id) on delete set null,approved_at timestamptz,created_at timestamptz not null default now(),check((expense_id is not null and revenue_id is null) or (expense_id is null and revenue_id is not null))
);
create table public.mileage(
 id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,trip_date date not null default current_date,start_location text,end_location text,round_trip boolean not null default false,purpose text,customer_project text,start_odometer numeric,end_odometer numeric,miles numeric not null default 0,rate_per_mile numeric(10,3) not null default 0,deduction_amount numeric(14,2) not null default 0,notes text,created_by uuid references auth.users(id) on delete set null,created_at timestamptz not null default now(),updated_at timestamptz not null default now()
);
create table public.invoices(
 id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,client_id uuid references public.clients(id) on delete set null,invoice_number text not null,invoice_date date not null default current_date,due_date date,status text not null default 'draft',subtotal numeric(14,2) not null default 0,tax_amount numeric(14,2) not null default 0,total_amount numeric(14,2) not null default 0,currency text not null default 'USD',notes text,payment_instructions text,created_by uuid references auth.users(id) on delete set null,created_at timestamptz not null default now(),updated_at timestamptz not null default now()
);
create table public.invoice_items(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,invoice_id uuid not null references public.invoices(id) on delete cascade,description text not null,quantity numeric not null default 1,rate numeric(14,2) not null default 0,amount numeric(14,2) not null default 0,sort_order integer not null default 0,created_at timestamptz not null default now());
create table public.user_activity(id bigint generated by default as identity primary key,organization_id uuid not null references public.organizations(id) on delete cascade,user_id uuid not null references auth.users(id) on delete cascade,activity_type text not null default 'app_use',occurred_at timestamptz not null default now());

create or replace function public.is_organization_member(org_id uuid) returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from public.organization_members where organization_id=org_id and user_id=auth.uid())$$;
revoke all on function public.is_organization_member(uuid) from public; grant execute on function public.is_organization_member(uuid) to authenticated;

alter table public.user_profiles enable row level security;alter table public.organizations enable row level security;alter table public.organization_members enable row level security;alter table public.signup_attempts enable row level security;alter table public.categories enable row level security;alter table public.accounts enable row level security;alter table public.clients enable row level security;alter table public.expenses enable row level security;alter table public.revenue enable row level security;alter table public.bank_transactions enable row level security;alter table public.reconciliations enable row level security;alter table public.mileage enable row level security;alter table public.invoices enable row level security;alter table public.invoice_items enable row level security;alter table public.user_activity enable row level security;

create policy profile_self on public.user_profiles for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy org_read on public.organizations for select to authenticated using(public.is_organization_member(id));
create policy org_update on public.organizations for update to authenticated using(public.is_organization_member(id)) with check(public.is_organization_member(id));
create policy membership_self_read on public.organization_members for select to authenticated using(user_id=auth.uid());
create policy categories_read on public.categories for select to authenticated using(organization_id is null or public.is_organization_member(organization_id));
create policy categories_org_write on public.categories for all to authenticated using(organization_id is not null and public.is_organization_member(organization_id) and not is_system) with check(organization_id is not null and public.is_organization_member(organization_id) and not is_system);
create policy accounts_org on public.accounts for all to authenticated using(public.is_organization_member(organization_id)) with check(public.is_organization_member(organization_id));
create policy clients_org on public.clients for all to authenticated using(public.is_organization_member(organization_id)) with check(public.is_organization_member(organization_id));
create policy expenses_org on public.expenses for all to authenticated using(public.is_organization_member(organization_id)) with check(public.is_organization_member(organization_id));
create policy revenue_org on public.revenue for all to authenticated using(public.is_organization_member(organization_id)) with check(public.is_organization_member(organization_id));
create policy bank_org on public.bank_transactions for all to authenticated using(public.is_organization_member(organization_id)) with check(public.is_organization_member(organization_id));
create policy reconcile_org on public.reconciliations for all to authenticated using(public.is_organization_member(organization_id)) with check(public.is_organization_member(organization_id));
create policy mileage_org on public.mileage for all to authenticated using(public.is_organization_member(organization_id)) with check(public.is_organization_member(organization_id));
create policy invoices_org on public.invoices for all to authenticated using(public.is_organization_member(organization_id)) with check(public.is_organization_member(organization_id));
create policy invoice_items_org on public.invoice_items for all to authenticated using(public.is_organization_member(organization_id)) with check(public.is_organization_member(organization_id));
create policy activity_own on public.user_activity for all to authenticated using(user_id=auth.uid() and public.is_organization_member(organization_id)) with check(user_id=auth.uid() and public.is_organization_member(organization_id));

insert into public.categories(name,category_type,is_system,sort_order) values
('Advertising & Marketing','expense',true,10),('Bank & Payment Fees','expense',true,20),('Business Meals','expense',true,30),('Computer & Equipment','expense',true,40),('Contractors','expense',true,50),('Education & Training','expense',true,60),('Insurance','expense',true,70),('Legal & Professional Services','expense',true,80),('Office Supplies','expense',true,90),('Rent & Lease','expense',true,100),('Repairs & Maintenance','expense',true,110),('Shipping & Postage','expense',true,120),('Software & Subscriptions','expense',true,130),('Taxes & Licenses','expense',true,140),('Telephone & Internet','expense',true,150),('Travel','expense',true,160),('Utilities','expense',true,170),('Vehicle & Transportation','expense',true,180),('Wages & Payroll','expense',true,190),('Other Business Expense','expense',true,200),('Uncategorized','expense',true,999),('Product Sales','revenue',true,10),('Service Revenue','revenue',true,20),('Consulting & Professional Services','revenue',true,30),('Subscription Revenue','revenue',true,40),('Interest Income','revenue',true,50),('Refunds & Reimbursements','revenue',true,60),('Other Income','revenue',true,70),('Uncategorized Income','revenue',true,999) on conflict do nothing;
